// General
export const SHOW_DELETE_MODAL = 'SHOW_DELETE_MODAL'

// User access

export const LOGIN = 'LOGIN'
export const REFRESH_TOKEN = 'REFRESH_TOKEN'
export const LOGGING_OUT = 'LOGGING_OUT';
export const LOGOUT = 'LOGOUT'
export const ENABLE_MFA = 'ENABLE_MFA'
export const SHOW_LOADER = 'SHOW_LOADER'
export const HIDE_LOADER = 'HIDE_LOADER'

// Forms & inputs

export const FORM_INPUT_CHANGE = 'FORM_INPUT_CHANGE'
export const UPLOAD_INPUT_CHANGE = 'UPLOAD_INPUT_CHANGE'
export const CLEAR_IMAGE_INPUT = 'CLEAR_IMAGE_INPUT'

// File transfer

export const UPLOAD_IMAGE_REQUEST = 'UPLOAD_IMAGE_REQUEST'
export const UPLOAD_IMAGE_SUCCESS = 'UPLOAD_IMAGE_SUCCESS'
export const UPLOAD_IMAGE_FAILURE = 'UPLOAD_IMAGE_FAILURE'
export const UPDATE_IMAGE_PREVIEW = 'UPDATE_IMAGE_PREVIEW';

// Users

export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE'

export const GET_USER_BY_ID_REQUEST = 'GET_USER_BY_ID_REQUEST'
export const GET_USER_BY_ID_SUCCESS = 'GET_USER_BY_ID_SUCCESS'
export const GET_USER_BY_ID_FAILURE = 'GET_USER_BY_ID_FAILURE'

export const EDIT_USER_REQUEST = 'EDIT_USER_REQUEST'
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS'
export const EDIT_USER_FAILURE = 'EDIT_USER_FAILURE'

export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST'
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE'

// Events

export const CREATE_EVENT_REQUEST = 'CREATE_EVENT_REQUEST'
export const CREATE_EVENT_SUCCESS = 'CREATE_EVENT_SUCCESS'
export const CREATE_EVENT_FAILURE = 'CREATE_EVENT_FAILURE'

export const FETCH_EVENT_REQUEST = 'FETCH_EVENT_REQUEST'
export const FETCH_EVENT_SUCCESS = 'FETCH_EVENT_SUCCESS'
export const FETCH_EVENT_FAILURE = 'FETCH_EVENT_FAILURE'

export const EDIT_EVENT_REQUEST = 'EDIT_EVENT_REQUEST'
export const EDIT_EVENT_SUCCESS = 'EDIT_EVENT_SUCCESS'
export const EDIT_EVENT_FAILURE = 'EDIT_EVENT_FAILURE'

export const DELETE_EVENT_REQUEST = 'DELETE_EVENT_REQUEST'
export const DELETE_EVENT_SUCCESS = 'DELETE_EVENT_SUCCESS'
export const DELETE_EVENT_FAILURE = 'DELETE_EVENT_FAILURE'

export const GET_MY_EVENT_REQUEST = 'GET_MY_EVENT_REQUEST'
export const GET_MY_EVENT_SUCCESS = 'GET_MY_EVENT_SUCCESS'
export const GET_MY_EVENT_FAILURE = 'GET_MY_EVENT_FAILURE'

export const FETCH_EVENTS_REQUEST = 'FETCH_EVENTS_REQUEST'
export const FETCH_EVENTS_SUCCESS = 'FETCH_EVENTS_SUCCESS'
export const FETCH_EVENTS_FAILURE = 'FETCH_EVENTS_FAILURE'

// Blog

export const CREATE_POST_REQUEST = 'CREATE_POST_REQUEST'
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS'
export const CREATE_POST_FAILURE = 'CREATE_POST_FAILURE'

export const FETCH_POST_REQUEST = 'FETCH_POST_REQUEST'
export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS'
export const FETCH_POST_FAILURE = 'FETCH_POST_FAILURE'

export const EDIT_POST_REQUEST = 'EDIT_POST_REQUEST'
export const EDIT_POST_SUCCESS = 'EDIT_POST_SUCCESS'
export const EDIT_POST_FAILURE = 'EDIT_POST_FAILURE'

export const DELETE_POST_REQUEST = 'DELETE_POST_REQUEST'
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS'
export const DELETE_POST_FAILURE = 'DELETE_POST_FAILURE'

export const GET_MY_POST_REQUEST = 'GET_MY_POST_REQUEST'
export const GET_MY_POST_SUCCESS = 'GET_MY_POST_SUCCESS'
export const GET_MY_POST_FAILURE = 'GET_MY_POST_FAILURE'

export const FETCH_POSTS_REQUEST = 'FETCH_POSTS_REQUEST'
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS'
export const FETCH_POSTS_FAILURE = 'FETCH_POSTS_FAILURE'

export const FETCH_TAGS_REQUEST = 'FETCH_TAGS_REQUEST'
export const FETCH_TAGS_SUCCESS = 'FETCH_TAGS_SUCCESS'
export const FETCH_TAGS_FAILURE = 'FETCH_TAGS_FAILURE'
export const SORT_POSTS = 'SORT_POSTS'
export const NO_RESULTS = 'NO_RESULTS'
export const CLEAR_SEARCH = 'CLEAR_SEARCH'

// Lots

export const CREATE_LOT_REQUEST = 'CREATE_LOT_REQUEST'
export const CREATE_LOT_SUCCESS = 'CREATE_LOT_SUCCESS'
export const CREATE_LOT_FAILURE = 'CREATE_LOT_FAILURE'

export const GET_LOT_REQUEST = 'GET_LOT_REQUEST'
export const GET_LOT_SUCCESS = 'GET_LOT_SUCCESS'
export const GET_LOT_FAILURE = 'GET_LOT_FAILURE'

export const EDIT_LOT_REQUEST = 'EDIT_LOT_REQUEST'
export const EDIT_LOT_SUCCESS = 'EDIT_LOT_SUCCESS'
export const EDIT_LOT_FAILURE = 'EDIT_LOT_FAILURE'

export const DELETE_LOT_REQUEST = 'DELETE_LOT_REQUEST'
export const DELETE_LOT_SUCCESS = 'DELETE_LOT_SUCCESS'
export const DELETE_LOT_FAILURE = 'DELETE_LOT_FAILURE'

export const GET_LOTS_REQUEST = 'GET_LOTS_REQUEST'
export const GET_LOTS_SUCCESS = 'GET_LOTS_SUCCESS'
export const GET_LOTS_FAILURE = 'GET_LOTS_FAILURE'

// Preoffers

export const CREATE_PREOFFER_REQUEST = 'CREATE_PREOFFER_REQUEST'
export const CREATE_PREOFFER_SUCCESS = 'CREATE_PREOFFER_SUCCESS'
export const CREATE_PREOFFER_FAILURE = 'CREATE_PREOFFER_FAILURE'

export const EDIT_PREOFFER_REQUEST = 'EDIT_PREOFFER_REQUEST'
export const EDIT_PREOFFER_SUCCESS = 'EDIT_PREOFFER_SUCCESS'
export const EDIT_PREOFFER_FAILURE = 'EDIT_PREOFFER_FAILURE'

export const DELETE_PREOFFER_REQUEST = 'DELETE_PREOFFER_REQUEST'
export const DELETE_PREOFFER_SUCCESS = 'DELETE_PREOFFER_SUCCESS'
export const DELETE_PREOFFER_FAILURE = 'DELETE_PREOFFER_FAILURE'

export const GET_MY_PREOFFERS_REQUEST = 'GET_MY_PREOFFERS_REQUEST'
export const GET_MY_PREOFFERS_SUCCESS = 'GET_MY_PREOFFERS_SUCCESS'
export const GET_MY_PREOFFERS_FAILURE = 'GET_MY_PREOFFERS_FAILURE'

export const GET_PREOFFERS_REQUEST = 'GET_PREOFFERS_REQUEST'
export const GET_PREOFFERS_SUCCESS = 'GET_PREOFFERS_SUCCESS'
export const GET_PREOFFERS_FAILURE = 'GET_PREOFFERS_FAILURE'

// Ads

export const CREATE_AD_REQUEST = 'CREATE_AD_REQUEST'
export const CREATE_AD_SUCCESS = 'CREATE_AD_SUCCESS'
export const CREATE_AD_FAILURE = 'CREATE_AD_FAILURE'

export const GET_AD_REQUEST = 'GET_AD_REQUEST'
export const GET_AD_SUCCESS = 'GET_AD_SUCCESS'
export const GET_AD_FAILURE = 'GET_AD_FAILURE'

export const EDIT_AD_REQUEST = 'EDIT_AD_REQUEST'
export const EDIT_AD_SUCCESS = 'EDIT_AD_SUCCESS'
export const EDIT_AD_FAILURE = 'EDIT_AD_FAILURE'

export const DELETE_AD_REQUEST = 'DELETE_AD_REQUEST'
export const DELETE_AD_SUCCESS = 'DELETE_AD_SUCCESS'
export const DELETE_AD_FAILURE = 'DELETE_AD_FAILURE'

export const GET_MY_AD_REQUEST = 'GET_MY_AD_REQUEST'
export const GET_MY_AD_SUCCESS = 'GET_MY_AD_SUCCESS'
export const GET_MY_AD_FAILURE = 'GET_MY_AD_FAILURE'

export const GET_MY_ADS_REQUEST = 'GET_MY_ADS_REQUEST'
export const GET_MY_ADS_SUCCESS = 'GET_MY_ADS_SUCCESS'
export const GET_MY_ADS_FAILURE = 'GET_MY_ADS_FAILURE'

export const GET_ADS_REQUEST = 'GET_ADS_REQUEST'
export const GET_ADS_SUCCESS = 'GET_ADS_SUCCESS'
export const GET_ADS_FAILURE = 'GET_ADS_FAILURE'