const bcrypt = require('bcrypt')
const otplib = require('otplib')

const createToken = require('../../utils/create-token')
const { userModel } = require('../../models/user')
const { CONSUMER_TOKEN_TYPE, REFRESH_TOKEN_TYPE } = require('../../utils/token-types')

const returnCredentials = (user, response) => {
    // Delete the fields that won't be showed in the response
    const userWithoutPassword = user.toJSON()
    delete userWithoutPassword.password
    delete userWithoutPassword.mfaSecret

    userWithoutPassword.token = createToken(user, CONSUMER_TOKEN_TYPE, '30m')
    userWithoutPassword.refreshToken = createToken(user, REFRESH_TOKEN_TYPE, '2d')

    response.json({
        user: userWithoutPassword
    })
}

module.exports = (request, response) => {
    userModel.findOne({ nickname: request.body.nickname })
        .then(user => {
            if (user) {
                // Match the login password with the password from database
                const match = bcrypt.compareSync(request.body.password, user.password)

                if (match) {
                    if (user.mfaEnabled) {
                        try {
                            // Validate the token generated by the app
                            const mfaTokenValid = otplib.authenticator.check(request.body.token, user.mfaSecret)

                            if (mfaTokenValid) {
                                returnCredentials(user, response)
                            } else {
                                console.error('Invalid MFA Token')
                                response.status(401).end()
                            }
                        } catch (err) {
                            console.error('Error validating MFA token', error)
                            response.status(401).end()
                        }
                    } else {
                        returnCredentials(user, response)
                    }
                } else {
                    console.error('Password does not match')
                    response.status(401).end()
                }
            } else {
                console.error('User not found')
                response.status(401).end()
            }
        }).catch(error => {
            console.error(error)

            response.status(500).json({
                message: 'Login error'
            })
        })
}